services:
  postgres:
    env_file: .env
    image: postgres:17-alpine
    ports:
      - 127.0.0.1:5432:5432
    volumes:
      - pg_data_webdev_project:/var/lib/postgresql/data

volumes:
  pg_data_webdev_project:
